#!/usr/bin/bash --

# ------------------------------------------------------
# 
#  tinybackup
#  ~~~~~~~~~~
#  the simplest GPG Folder Backup
#
#  Author:  David Valin <hola@davidvalin.com>
#  License: Apache License
#
# ------------------------------------------------------

cmd=$1

if [[ "$cmd" == "b" ]]; then

    echo -e "\nBACKUP A FOLDER"
    echo -e "__________________________________\n"

    backup_folder=$2
    backup_destination_folder=$3
    backup_name=$4
    gpg_pub_key_id=$5
    NOW=$(date +"%Y%m%d.%H%M")
    backup_name="$backup_name.$NOW.tgz"
    enc_output="$backup_name.gpg"

    echo " [x] Backup mode set"
    echo " [x] Folder to backup: $backup_folder"
    echo " [x] GPG public key: $gpg_pub_key_id"
    echo " [x] Backup destination folder: $backup_destination_folder"
    echo " [x] Backup name: $backup_name"
    echo ""

    read -p "    Press 'y' to continue or any other key to exit: " response

    if [[ "$response" == "y" || "$response" == "Y" ]]; then
      echo ""
      echo " [x] Backup started at $NOW..."
      echo ""
      mkdir -p $backup_destination_folder
      # using memory only, archive -> compress -> encrypt -> split
      tar --absolute-names -cf - "$backup_folder" | gzip | pv | gpg --encrypt --armor --recipient "$gpg_pub_key_id" | split -b 100M - "$backup_destination_folder/$enc_output."  
    else
      echo "Exiting..."
      exit 1
    fi
    exit 1
fi

if [[ "$cmd" == "r" ]]; then

    echo -e "\nRECOVER FOLDER BACKUP"
    echo -e "__________________________________\n"

    backup_name=$2
    recover_root_folder=$3
    gpg_private_key_id=$4
    NOW=$(date +"%Y%m%d.%H%M")

    echo " [x] Recover mode set"
    echo " [x] Recovering $backup_name..."
    echo " [x] Recover root folder: $recover_root_folder"
    echo " [x] GPG key: $gpg_private_key_id"
    echo ""
    echo " Input files:"

    mkdir -p $recover_root_folder

    # using memory only: read -> decrypt -> uncompress in target
    for file in "$backup_name."*; do
      echo "   $file"
    done
    echo ""
    echo " [x] Recover started at $NOW..."
    cat "$backup_name."* | gpg --decrypt --recipient "$gpg_private_key_id" --output - | gunzip | tar -xf - -C "$recover_root_folder"
    exit 1
fi

